### ISSUE TITLE
how to get the correct camera paramter 

### ISSUE THREAD

**Issue by ForrestPi** [hygenie1228/ClothWild_RELEASE#2]
Hi, 
I had tried using Pose2pose to get pose2pose_result.json(according to https://github.com/hygenie1228/ClothWild_RELEASE/issues/1)
and got the reasonable result like 
![render_original_img_body](https://user-images.githubusercontent.com/12846142/187897133-fd3932cb-a45f-40b2-8c95-db93b461c517.jpg)
but when I tried (https://github.com/hygenie1228/ClothWild_RELEASE/blob/main/demo/demo.py)

**Comment by ForrestPi** [comment]
the result blew
![render_original_img](https://user-images.githubusercontent.com/12846142/187897773-a435b094-89bb-45be-9c21-1d9b729081ce.jpg)

**Comment by ForrestPi** [comment]
maybe the camera paramter got woring. how to get the correct camera paramter?
 long trousers and short trousers got woring.

**Comment by hygenie1228** [comment]
Thank you for your interest in our work.

There are a few things I want to check.

1. Did you put the correct value in the bbox variable below?
https://github.com/hygenie1228/ClothWild_RELEASE/blob/main/demo/demo.py#L65

2. Is the demo image provided by the repository running properly?

If it still doesn't work after checking two, please give me a demo image.
I'll check the code.

**Comment by ForrestPi** [comment]
@hygenie1228  yeah I used the value in the bbox by [labelme](https://github.com/wkentaro/labelme).
box="154, 67, 400, 914"
[data.zip](https://github.com/hygenie1228/ClothWild_RELEASE/files/9487930/data.zip)

**Comment by hygenie1228** [comment]
You should also change bbox variable at https://github.com/hygenie1228/ClothWild_RELEASE/blob/main/demo/demo.py#L65

It seems that the bbox variable is not modified given by default in the demo file.

I can observe the similar result when not changing the bbox variable as below.

![image](https://user-images.githubusercontent.com/69622221/188406421-056cec27-9226-4365-a915-77da66dbbb11.png)

But, when changing the bbox variable at (https://github.com/hygenie1228/ClothWild_RELEASE/blob/main/demo/demo.py#L65) with "bbox = [154, 67, 400, 914] ", I can get correct rendering result as below.

![image](https://user-images.githubusercontent.com/69622221/188406345-e0d268c7-299b-4d1f-a636-4124a86df83a.png)

On the one hand, we can observe that the rendered surface is unusual in your example.
I couldn't check the phenomenon, but it seems to be a dependency problem in pytorch3d.

Please check the dependency based on your pytorch/cuda version. Refer to below.
https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md

**Comment by ForrestPi** [comment]
@hygenie1228 thanks
