### ISSUE TITLE
Test Error

### ISSUE THREAD

**Issue by BaymaxShao** [hygenie1228/ClothWild_RELEASE#5]
Sorry to bother you!
I have trained a model, but when I evaluate CD and BCC, I meet two problems below:
1. When I evaluate CD on dataset PW3D, I get an error as the image below shows:
![245af504782fd183c745ab104cca26c](https://user-images.githubusercontent.com/91866296/215097631-444f1ca2-6830-4b84-8785-da8f083860cd.png)
By debugging, I find the variable 'targets' is empty in line51, main/test.py

2. When I evaluate BCC on dataset MSCOCO, I get wrong results below:
![7f16d4f0949b4c729a51b4befb0760f](https://user-images.githubusercontent.com/91866296/215098168-0fa4bd0e-ebc6-442d-b272-569c8f145578.png)
By debugging, I find the variable 'gt_ids' is an empty list [] in MSCOCO.py

I have tried downloading the dataset again and using the checkpoint you offer, but I get the same situation.
So I can't figure out what's wrong.

**Comment by hygenie1228** [comment]
Thanks for your interest in our work.

Through your debugging, I can guess what the two symptoms have in common:
Target data required for evaluation was properly not loaded.

The problem could be in two parts: 1) data fetch or 2) data transfer.

1) Please check if the data is fetched properly on each dataset.

PW3D: targets['smpl_mesh']
https://github.com/hygenie1228/ClothWild_RELEASE/blob/main/data/PW3D/PW3D.py#L113
MSCOCO: targets['smpl_cloth_idx']
https://github.com/hygenie1228/ClothWild_RELEASE/blob/main/data/MSCOCO/MSCOCO.py#L257

2) Please check the data transfer code in main/model.py.

https://github.com/hygenie1228/ClothWild_RELEASE/blob/main/main/model.py#L126
Keys such as 'smpl_mesh_target' or 'smpl_cloth_idx_target' must exist in targets.

If you've checked both and still have problems, please inform me.
Thank you.

**Comment by BaymaxShao** [comment]
Thanks for your help! Problems have been solved.
