### ISSUE TITLE
How can i change the color of cloth in demo

### ISSUE THREAD

**Issue by 30410B** [hygenie1228/ClothWild_RELEASE#8]
When i run demo, i fint it can't change the color of colthes in body, how can i use different colors in demo

**Comment by hygenie1228** [comment]
Hi, could you re-check these parameters?

https://github.com/hygenie1228/ClothWild_RELEASE/blob/f166dbdadc8ae691830811801a4c605efc6c7326/main/config.py#L46

**Comment by 30410B** [comment]
I have changed this parameters, but it not works
![K4DU}63LB4(@CX58`3A0MUP](https://github.com/user-attachments/assets/e44163f7-b731-4255-b217-c4d9e9b8ac46)
![render_cropped_img](https://github.com/user-attachments/assets/e1e4968c-7e47-42f5-a72a-4452bbbb4c9c)

**Comment by hygenie1228** [comment]
Oh, it does not support the colors in rendering,
The parameters are related to change the colors in .obj file.
If you want to adapt colors in the rendering pipeline, I suggest to revise the below code line (verts_rgb).

https://github.com/hygenie1228/ClothWild_RELEASE/blob/main/common/utils/postprocessing.py#L71

**Comment by 30410B** [comment]
> Oh, it does not support the colors in rendering, The parameters are related to change the colors in .obj file. If you want to adapt colors in the rendering pipeline, I suggest to revise the below code line (verts_rgb).
> 
> https://github.com/hygenie1228/ClothWild_RELEASE/blob/main/common/utils/postprocessing.py#L71

Thank you for your response. But when i use an online link to open this obj file, it still no works
![~WW2P7`2@ I6 IU{%GD~ R0](https://github.com/user-attachments/assets/d7eb1f22-66fe-4ffc-b831-5153f9c3a5ef)

**Comment by 30410B** [comment]
> Oh, it does not support the colors in rendering, The parameters are related to change the colors in .obj file. If you want to adapt colors in the rendering pipeline, I suggest to revise the below code line (verts_rgb).
> 
> https://github.com/hygenie1228/ClothWild_RELEASE/blob/main/common/utils/postprocessing.py#L71
Thank you， I have finished this problem， i use another link to open this file， it works， thanks for your help.
![Uploading image.png…]()

**Comment by 30410B** [comment]
it works![@)K$_B760N(D2R$H%Y7W{CO](https://github.com/user-attachments/assets/8af5dc9a-6baf-4948-a177-7b0f239faab1)
